package kz.h3project.model.user.enums;

public enum PermissionDic {

    CREATE_USER, READ_USER, WRITE_USER, DELETE_USER,
    READ_ORDER, WRITE_ORDER, DELETE_ORDER,
    READ_HOSPITAL, WRITE_APPOINTMENT,
    MANAGE_CONTENT, MANAGE_SYSTEM,
    READ_REPORTS
}
